const quotes = [
    { text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "If you want to shine like a sun, first burn like a sun.", author: "APJ Abdul Kalam" },
    { text: "Arise, awake, and stop not until the goal is reached.", author: "Swami Vivekananda" },
    { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
    { text: "Dream, dream, dream. Dreams transform into thoughts and thoughts result in action.", author: "APJ Abdul Kalam" },
    { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
    { text: "Take up one idea. Make that one idea your life – think of it, dream of it, live on that idea.", author: "Swami Vivekananda" },
    { text: "You cannot change your future, but you can change your habits, and surely your habits will change your future.", author: "APJ Abdul Kalam" },
    { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { text: "Do not wait for leaders; do it alone, person to person.", author: "Mother Teresa" },
    { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    { text: "The future depends on what we do in the present.", author: "Mahatma Gandhi" },
    { text: "To succeed in your mission, you must have single-minded devotion to your goal.", author: "APJ Abdul Kalam" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "It's not the years in your life that count. It's the life in your years.", author: "Abraham Lincoln" },
    { text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    { text: "I have no special talent. I am only passionately curious.", author: "Albert Einstein" },
    { text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "In the end, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King Jr." },
    { text: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    { text: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The best time to plant a tree was 20 years ago. The second-best time is now.", author: "Chinese Proverb" },
    { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "Your time is limited, don't waste it living someone else's life.", author: "Steve Jobs" },
    { text: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "Act as if what you do makes a difference. It does.", author: "William James" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama"}
]
